apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: np
spec:
  selector:
    app: {{ .Values.appName }}
  type: NodePort
  ports:
    - port: 2000
      targetPort: 80
      nodePort: 30010
      protocol: TCP
